default:
  @just --list

bios:
  systemctl reboot --firmware-setup

update:
  rpm-ostree upgrade
  flatpak update -y
  distrobox upgrade -a

run-firstboot:
  /usr/libexec/firstboot

setup: run-firstboot update
