ARG FEDORA_MAJOR_VERSION=37
FROM quay.io/fedora-ostree-desktops/silverblue:${FEDORA_MAJOR_VERSION} AS builder

ARG NVIDIA_MAJOR_VERSION="${NVIDIA_MAJOR_VERSION:-530}"
ARG FEDORA_MAJOR_VERSION

COPY justfile /tmp/build/nvidia-just/justfile
COPY build.sh /tmp/build.sh

ADD certs /tmp/certs

ADD nvidia-addons.spec /tmp/nvidia-addons/nvidia-addons.spec

ADD https://nvidia.github.io/nvidia-docker/rhel9.0/nvidia-docker.repo \
  /tmp/nvidia-addons/rpmbuild/SOURCES/nvidia-container-runtime.repo

ADD https://nvidia.github.io/nvidia-docker/rhel9.0/nvidia-docker.repo \
  /etc/yum.repos.d/nvidia-container-runtime.repo

ADD etc/nvidia-container-runtime/config-rootless.toml \
  /tmp/nvidia-addons/rpmbuild/SOURCES/config-rootless.toml

ADD https://raw.githubusercontent.com/NVIDIA/dgx-selinux/master/bin/RHEL9/nvidia-container.pp \
  /tmp/nvidia-addons/rpmbuild/SOURCES/nvidia-container.pp

ADD etc/sway/environment /tmp/nvidia-addons/rpmbuild/SOURCES/environment

RUN rpm-ostree install \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
  rpm-ostree install \
  rpmfusion-nonfree-release  \
  rpmfusion-free-release  \
  --uninstall=rpmfusion-free-release-$(rpm -E %fedora)-1.noarch  \
  --uninstall=rpmfusion-nonfree-release-$(rpm -E %fedora)-1.noarch

RUN /tmp/build.sh

RUN rpm -ql /tmp/nvidia-addons/rpmbuild/RPMS/*/*.rpm
