name: Build and Push OCI Image

on:
  push:
    branches:
      - main
  # TODO: Remove pull_request trigger
  pull_request:

env:
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/fedora-silverblue

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      #- uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.BASE_IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: List tags
        run: |
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo "Labels:"
          echo "${{ steps.meta.outputs.labels }}"
