name: Build and Push OCI Image

on:
  schedule:
    - cron: '0 0,12 * * *' # Twice daily
  push:
    branches:
      - main
  pull_request:

env:
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/silverblue
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        fedora-version: [ 37, 38 ]
        include:
          - fedora-version: 37
            is-stable: true
          - fedora-version: 38
            is-latest: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags (main)
        if: github.ref == 'refs/heads/main'
        run: |
          DEFAULT_TAGS=()
          TAG_SUFFIX="-${{ matrix.fedora-version }}"

          # Add :<version> tag - e.g. :37
          DEFAULT_TAGS+=("${{ matrix.fedora-version }}")
          # Add date tag - e.g. :20230101000000-<version>
          DEFAULT_TAGS+=("$(date -u +%Y%m%d%H%M%S)-${{ matrix.fedora-version }}")
          # Add short SHA tag - e.g. :abcdef-<version>
          DEFAULT_TAGS+=("${GITHUB_SHA::8}-${{ matrix.fedora-version }}")
          # Add full SHA tag - e.g. :abcdef0123456789abcdef0123456789abcdef-<version>
          DEFAULT_TAGS+=("${GITHUB_SHA}-${{ matrix.fedora-version }}")

          # Add :latest tag if this is the latest Fedora version (inc. pre-releases)
          if [ "${{ matrix.is-latest }}" = "true" ]; then
            DEFAULT_TAGS+=("latest")
          fi

          # Add :stable tag if this is the latest stable Fedora version
          if [ "${{ matrix.is-stable }}" = "true" ]; then
            DEFAULT_TAGS+=("stable")
          fi

          echo "TAGS=${DEFAULT_TAGS[*]}" >> $GITHUB_ENV

      - name: Generate tags (Pull Request)
        if: github.event_name == 'pull_request'
        run: |
          DEFAULT_TAGS+=("pr-${{ github.event.pull_request.number }}-${{ matrix.fedora-version }}")
          DEFAULT_TAGS+=("test-${{ matrix.fedora-version }}")
          echo "TAGS=${DEFAULT_TAGS[*]}" >> $GITHUB_ENV

      - name: Build and Push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.BASE_IMAGE }}
          tags: ${{ env.TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build_args: |
            FEDORA_MAJOR_VERSION=${{ matrix.fedora-version }}
