name: Cleanup images

on:
  schedule:
    - cron: '0 0 * * *' # Daily
  # TODO: Remove this once we're sure it's working
  pull_request:

env:
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/silverblue

jobs:
  delete-containers:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.BASE_IMAGE }}
          package-type: container
          min-versions-to-keep: 1 # TODO: Set this to a larger number once we're sure it's working
          ignore-versions: 'latest(-\d+)?'
          token: ${{ secrets.GITHUB_TOKEN }}
