name: Release

on:
  pull_request:

jobs:
  publish-iso:
    runs-on: ubuntu-latest
    container: fedora:latest
    strategy:
      matrix:
        fedora-version: [ 37, 38 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Kickstart
        id: generate-kickstart
        shell: bash
        run: |
          dnf install -y gettext
          # Render the kickstart file from the kickstart.ks.tpl template using envsubst
          cat kickstart.ks.tpl | envsubst > kickstart.ks
          echo "KICKSTART_FILE_PATH=$(pwd)/kickstart.ks" >> $GITHUB_ENV
        env:
          IMAGE_OWNER: ${{ github.repository_owner }}
          IMAGE_NAME: silverblue
          IMAGE_TAG: ${{ matrix.fedora-version }}

      - name: Generate ISO
        uses: ./.github/actions/generate-iso
        id: generate-iso
        with:
          filename: silverblue-${{ matrix.fedora-version }}
          # Currently only the development branch includes support for booting from OCI images
          installer-repo: development
          kickstart-file-path: ${{ env.KICKSTART_FILE_PATH }}

      - name: Upload ISO to Workflow Artifact
        uses: actions/upload-artifact@v3
        with:
          name: silverblue-${{ matrix.fedora-version }}
          path: |
            ${{ steps.generate-iso.outputs.iso-path }}
            ${{ steps.generate-iso.outputs.checksum-path }}
          if-no-files-found: error
